language: C++
sudo: required 

script: (cd src/tbb/; make); 
        cd src/tbb/examples/task_group/sudoku 
        c++ -std=c++11 -O2 -DNDEBUG -Wl,-rpath,../../../lib -o channel channel.cpp -ltbb

notifications:
    email: false

