#pragma once
#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H

#define select_0(channel1, true, result, nullptr, false, std::this_thread::sleep_for(std::chrono::seconds(5))) \
{ \
while (true) \
{ \
if (true) \
{ \
if (channel1.read(&result, false)) \
{ \
	        { \
		        results.push_back(result); \
	        } \
break;\
} \
} \
else \
{ \
if (channel1.write(result, false)) \
{ \
	        { \
		        results.push_back(result); \
	        } \
break;\
} \
} \
if (false) \
{ \
} \
else \
{\
std::this_thread::sleep_for(std::chrono::seconds(5));\
	        { \
		        return results; \
	        } \
}\
} \
}


// =========================== END AUTOGENERATED SOURCE CODE ==================================

#endif
