#pragma once
#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H

#define select_0(channel1, true, message1, channel2, true, message2, channel3, false, message3, channel_GuiSim, true, nullptr) \
{ \
if (true) \
{ \
if (true) \
{ \
if (channel1.read(&message1, false)) \
{ \
        { \
            printf("1"); \
        }    \
break;\
} \
} \
else \
{ \
if (channel1.write(message1, false)) \
{ \
        { \
            printf("1"); \
        }    \
break;\
} \
} \
if (true) \
{ \
if (channel2.read(&message2, false)) \
{ \
        { \
            printf("2"); \
        } \
break;\
} \
} \
else \
{ \
if (channel2.write(message2, false)) \
{ \
        { \
            printf("2"); \
        } \
break;\
} \
} \
if (false) \
{ \
if (channel3.read(&message3, false)) \
{ \
        { \
            printf("Succeeded to write on channel 3\n"); \
        } \
break;\
} \
} \
else \
{ \
if (channel3.write(message3, false)) \
{ \
        { \
            printf("Succeeded to write on channel 3\n"); \
        } \
break;\
} \
} \
if (true) \
{ \
if (channel_GuiSim.read(nullptr, false)) \
{ \
        { \
            printf("Gui"); \
        } \
break;\
} \
} \
else \
{ \
if (channel_GuiSim.write(nullptr, false)) \
{ \
        { \
            printf("Gui"); \
        } \
break;\
} \
} \
        { \
            print ("nothing"); \
        } \
} \
}


// =========================== END AUTOGENERATED SOURCE CODE ==================================

#endif
