#pragma once
#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H

#define select_0(channel1, true, message1, channel2, true, message2, channel3, false, message3, channel_GuiSim, true, nullptr) \
{ \
if (true) \
{ \
if (true) \
{ \
if (channel1.read(message1, false)) \
        { \
            printf("1"); \
        }    \
} \
else \
{ \
if (channel1.write(*message1, false)) \
{ \
printf("Succeeded to write on channel1\n"); \
break; \
} \
} \
if (true) \
{ \
if (channel2.read(message2, false)) \
        { \
            printf("2"); \
        } \
} \
else \
{ \
if (channel2.write(*message2, false)) \
{ \
printf("Succeeded to write on channel2\n"); \
break; \
} \
} \
if (false) \
{ \
if (channel3.read(message3, false)) \
        { \
            printf("Succeeded to write on channel 3\n"); \
        } \
} \
else \
{ \
if (channel3.write(*message3, false)) \
{ \
printf("Succeeded to write on channel3\n"); \
break; \
} \
} \
if (true) \
{ \
if (channel_GuiSim.read(nullptr, false)) \
        { \
            printf("Gui"); \
        } \
} \
else \
{ \
if (channel_GuiSim.write(nullptr, false)) \
{ \
printf("Succeeded to write on channel_GuiSim\n"); \
break; \
} \
} \
        { \
            print ("nothing"); \
        } \
} \
}


// =========================== END AUTOGENERATED SOURCE CODE ==================================

#endif
